version: "3.7"
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: dockette/adminer
    restart: always
    ports:
      - 8080:80
